### ISSUE TITLE
GAN Compression

### ISSUE THREAD

**Issue by deepseek** [masyagin1998/robin#10]
@masyagin1998 
https://github.com/mit-han-lab/gan-compression
https://arxiv.org/pdf/2003.08936.pdf

**Comment by masyagin1998** [comment]
??

**Comment by deepseek** [comment]
A new open-source image-to-image technique have been released, showing promising results.
- You initially train a Teacher model, then Distill and Prune it to create a smaller Student model, inwhich you will extract many smaller students, and finally choose the best, perhaps even fintune it.

1.  The result is creating a `very small model`, perhaps 2-4 MB.
2.  Very `fast inferencing on a cpu`.
3. Having `reasonable accuracy`.

**https://hanlab.mit.edu/files/gan_compression/**
