### ISSUE TITLE
run code problem

### ISSUE THREAD

**Issue by justinner** [masyagin1998/robin#2]
Hi,masyagin,It is my glad to learn your method,when I run the train.py ,the error occured as follow:
File "train.py", line 391, in main
    for i in range(len(os.listdir(os.path.join(args.input, 'in'))))]
FileNotFoundError: [Errno 2] No such file or directory: './input/in'
I thought I should create my dataset,but I don not know how to do and modify the path ,could you help me?Thanks very much.

**Comment by masyagin1998** [comment]
Hello!
I'm going to write better documentation for all my code, but I don't have time for it now (maybe after New Year celebration).

To run my code You should do 4 main steps:
1) Download, for example, DIBCO dataset from provided in `readme` link.
2) In `src/dataset` create directory `input` and put unarchived `DIBCO` data to it, and run `dataset.py`. After it's running You'll get `src/dataset/output` directory with training data. 
3) You should move `src/dataset/output` to `src/unet/input`. So now You have training data for Neural Network.
4) Now you can run `train.py`.

**Comment by masyagin1998** [comment]
If You want to create Your own dataset, You should make it in the same format as my dataset-examples: DIBCO, LRDE, Borders and Palm Leaf, and give it to `src/unet/dataset.py`.

**Comment by justinner** [comment]
OK,Thanks very much,I will try to run according to your guidence,thanks!
