### ISSUE TITLE
Achieving Speed and Accuracy 

### ISSUE THREAD

**Issue by deepseek** [masyagin1998/robin#5]
@masyagin1998 hi,

Robin seem to be very interesting and fast, I am currently working on a semantic segmentation code, and I want to achieve the highest prediction `fps` frames per second and accuracy along with memory efficiency, so what do you recommend?

- Should I use patches in training & prediction, or do you recommend something else?
- Does training fully rely on the cropped patches of images, or does it further have some tricks like (resizing, downscaling, upscaling, etc...)?

**Comment by masyagin1998** [comment]
Hello!
1) Yes, training & prediction uses cropped parts of images.
2) Training shouldn't rely only on the cropped image parts, it is better to use "tricks" (augmentation), because using only cropped images - you need too big dataset.

**Comment by deepseek** [comment]
Thank you :)
