### ISSUE TITLE
Missing TensorFlow in requirements.txt

### ISSUE THREAD

**Issue by krishvishal** [masyagin1998/robin#6]
tensorflow is missing from requirements.txt. Can someone add it ?

**Comment by masyagin1998** [comment]
Hi!
There is no TF in requirements, because Keras can use different types ob backend.
If You try to run pipreqs for robin, You'll see, that there is no TF in reqs, only:
imageio==2.4.1
alt_model_checkpoint==1.0.1
Keras==2.2.4
opencv_python==3.4.3.18
numpy==1.14.5
Augmentor==0.2.6
Pillow==6.1.0
