### ISSUE TITLE
Any tools to make my own dataset?

### ISSUE THREAD

**Issue by kli017** [masyagin1998/robin#7]
Hello, thank you for the awesome project. I tried the base model on my own images and found that some image does not perform very well. I want to finetune the weights on my own dataset. May I know how to made the ground truth of the document images? Thanks!

**Comment by masyagin1998** [comment]
Hello!

As I understood from Your message, You need a strategy to create pairs of original and ground-truth documents for new dataset and than, train neural network on it?

It is sad, but making ground-truth is hard and boring process. You can't make it fully automatized. Best way is to process images with neural network with existing waits, and than find "bad" parts of images and process them by your hand. So You combine work of neural network and your own hand-work.
